### ISSUE TITLE
Metamask Ledger-connected account can't process any transaction on Binance Smart Chain

### ISSUE THREAD

**Issue by snajjar** [MetaMask/metamask-extension#10132]
**Describe the bug**

When adding the [Binance Smart Chain as a network](https://academy.binance.com/en/articles/connecting-metamask-to-binance-smart-chain) to Metamask, I was able to send funds to my ledger-connected account and display coins.
But when trying to use smart contracts, swap tokens or send them away, any transaction started fails, even though my ledger nano is connected. My tokens are blocked.

[It seems that I'm not the only one in this situation](https://www.reddit.com/r/Metamask/comments/k3mhgt/metamask_account_ledger_account_having_issues/).

I believe Metamask is unable to sign the transactions correctly with the ledger device.

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

1) Create a metamask wallet and connect it to a ledger nano device
2) Add the binance smart chain to the list of networks (see above link)
3) Send some funds to your wallet (use the "ETH" address on your BSC network)
4) try to do anything with your tokens (DEX Swap, smart contract, sending tokens away, liquidity pools, etc)

You'll see transactions pending undefinitely, until you close your browser, they will appear as failed (saying in a notification: "")

**Expected behavior**

Any transaction should work as expected.

**Screenshots**

![image](https://user-images.githubusercontent.com/1130216/103460202-b5389100-4d14-11eb-8179-69fd90de7150.png)

**Browser details (please complete the following information):**
 - OS: Windows 10
 - Hardware Wallet: Ledger Nano X
 - Browser: Brave 1.19.72
 - MetaMask Version: 8.1.9

**Additional context (Error Messages, etc.)**

Metamask when restart send a notification:

    Error: Transaction found as "approved" during boot - possibly stuck during signing

I can provide the state logs if needed.

**Comment by mfgmfgmfgmfg** [comment]
Its issue with ledger not promting for sign have same issue hope for ledger and meta solve it quick as its pain in ass...I use to have problem with ETH also, but it somehow working....but really this is problem number one!

**Comment by rekmarks** [comment]
@snajjar, thank you for reporting this issue. A couple of clarifying questions:

1. Is your Ledger firmware and BNB app up-to-date?
2. Can you interact with the Binance chains in MetaMask using your normal MetaMask accounts?

**Comment by dpazdan** [comment]
Contract data needs to be set to “allowed” on the ledger device, under > binance smart chain app > settings.

**Comment by snajjar** [comment]
Hello, 

I finally found the solution. Before I can process a transaction, I first need to:
1) Close Ledger live
2) Unlock my ledger
3) Open the Ethereum App on the ledger (even though i'm on Binance Smart Chain network).

OFC you need to have smart contract enable in the Ethereum apps settings.

Nothing to fix then, but I still think metamask should show some instructions when working with a Ledger wallet, I've seen many other users stuck on this problem on reddit.

**Comment by rekmarks** [comment]
Thank you @snajjar. I'm glad your problem is resolved.

You are absolutely correct that there are many UX improvements to be made for our Ledger integration. We have many of the documented internally, but if you have any specific suggestions, I encourage you to open a new issue.

I will now close this issue.

**Comment by mfgmfgmfgmfg** [comment]
Hi

Ledger all up to dáte
Yes they working normály Outside ledger

S pozdravem
Mirek Hanzlicek

**Comment by mfgmfgmfgmfg** [comment]
This is not possible under bsc and on eth i have it allowed

S pozdravem
Mirek Hanzlicek

**Comment by mfgmfgmfgmfg** [comment]
No not solved is working only on metamask with no ledger...i need it to work on ledger account which is not

S pozdravem
Mirek Hanzlicek

**Comment by mfgmfgmfgmfg** [comment]
Thx 

this solution working...what if same happened with ETH chain is not promting for sign?

S pozdravem
Mirek Hanzlicek

**Comment by Pbear1** [comment]
Hi, I have exactly the same issue as snajjar - I followed the process carefully to close ledger Live, unlock Nano X, Open Ethereum App... yet no way to make it work
When adding the Binance Smart Chain as a network to Metamask, I was able to send funds to my ledger-connected account and display coins.
But when trying to use smart contracts, swap tokens or send them away, any transaction started fails, even though my ledger nano is connected. My tokens are blocked.
I am not prompted to accept the transaction on the Nano X and Pancakeswap will wait forever the confirmation
At the end all transaction fail and flashes Error: Transaction found as "approved" during boot - possibly stuck during signing
Need help to access my coins - thank you

**Comment by Charles1104** [comment]
Hi, I am having exactly the same issue. I have my metamask connected to my Ledger X. I have added the BSC network and can see my BNB funds. I then go to pancakeswap and every time I want to do a transaction, I click on approve and then it load indefinitely...

**Comment by Pbear1** [comment]
Hi, I am still stuck.  I tried again and again. Still the same issue. The transaction looks all ok in Pancakeswap, then Metamask is prompting me to validate the transaction (a simple swap of BNB to exchange against a common BSC token)  as well. I do = last step would be to finally validate the transaction on the Nano but the Nano does not prompt.  It is in the open Eth App.  There is nothing to validate in Nano and yet Pancakeswap is waiting forever for a validation that cannot be made... no progress... contract data is set to "allowed" ... all firmwares are uptodate...

**Comment by lieberscott** [comment]
Same problem here. MetaMask connected to Ledger device. MetaMask shows BNB tokens on Binance Smart Chain network. I'm connected to PancakeSwap. It shows I have BNB tokens in my MetaMask. I try to swap, it await confirmation. I confirm on MetaMask, but there's nothing that gets prompted on the Ledger device and the transaction is pending confirmation and never completed.

**Comment by lieberscott** [comment]
I want to update my comment. I updated all the firmware, closed all the applications (MetaMask, Ledger Live, Chrome, etc.), restarted my computer, and then started it back up. I plugged in my Ledger (did not open Ledger Live, not sure if this matters or not), went to PancakeSwap and was able to make a swap (it asked for confirmation on my device). Hope this helps.

**Comment by dpazdan** [comment]
@lieberscott @Pbear1 @Charles1104 on the ledger, go to the ethereum app, please confirm you have Contract data set to "allowed"

**Comment by Charles1104** [comment]
Hi,

Also updated all the firmware on my ledger nano x, restarted my computer
then tried again and it worked. Thanks all for your help.

**Comment by cam8099sa** [comment]
HELLO EVERYONE, I HAVE BEEN DEALING WITH THE SAME ISSUE FOR THE LAST COUPLE OF DAYS, BUT I GOT IT FIXED.

1. MAKE SURE LEDGER LIVE IS UPTO DATE AND ALL YOUR APPS IN LEDGER LIVE IS ALSO UPDATED.
2.  CLOSE LEDGER LIVE
3. CLOSE YOU BROWSER
4. CONNECT LEDGER TO LAPTOP
5. UNLOCK YOUR LEDGER USING PIN NUMBER
6. OPEN THE ETHEREUM APP ON THE LEDGER, UNDER CONTRACT DATA MAKE SURE IT IS SET TO "ALLOWED"
7.  OPEN THE ETHEREUM APP ON THE LEDGER AND MAKE SURE IT IS SET ON "APPLICATION IS READY"
8.  NOW OPEN YOUR BROWSER
9.  SIGN INTO METAMASK AND CONNECT LEDGER
10.  PROCEED WITH CONTRACTS, APPROVE THEM AS NORMAL
11.  CHECK YOUR LEDGER AND MAKE SURE TO APPROVE ANY CONTRACTS THAT POP UP ON THE LEDGER.

FOLLOWING THESE STEPS SHOULD FIX YOUR PROBLEM WITH "STALLED OUT TRANSACTIONS" ON METAMASK WHILE YOUR LEDGER IS CONNECTED.
