### ISSUE TITLE
code: -32602 message: "Invalid transaction envelope type: specified type 0x0 but including maxFeePerGas and maxPriorityFeePerGas requires type: 0x2

### ISSUE THREAD

**Issue by VexyCats** [MetaMask/metamask-extension#11824]
**Describe the bug**

Trying to send a simple ETH transfer from a dapp - dapp is suggesting a gas price based on pre-EIP-1559, yet metamask 10.0.0 is work EIP-1559

**Steps to reproduce (REQUIRED)**
Steps to reproduce the behavior, libraries used with version number, and/or any setup information to easily reproduce:

Send an eth transaction with a gas limit of say "30000", normal web3 sendTransaction with a value. 

**Expected behavior**
To let the user send X amount of ETH to XYZ address.

**Screenshots**

**Browser details (please complete the following information):**
 Metamask 10.0.0

**Additional context (Error Messages, etc.)**

RPC Error: Invalid transaction envelope type: specified type "0x0" but including maxFeePerGas and maxPriorityFeePerGas requires type: "0x2" code: -32602

**Comment by lydianblues** [comment]
Same thing here, on both the Chrome and Firefox browser extensions:

 MetaMask - RPC Error: Invalid transaction envelope type: specified type "0x0" but including maxFeePerGas and maxPriorityFeePerGas requires type: "0x2" {code: -32602, message: "Invalid transaction envelope type: specified type …Gas and maxPriorityFeePerGas requires type: \"0x2\""}

**Comment by iObedson** [comment]
I'm having a similar 
![Metamask error](https://user-images.githubusercontent.com/86617200/129362789-343aa398-e79f-452d-8dc4-4c52e5ef91a3.png)

issue!


Invalid transaction envelope type: specified type "0x0" but including maxFeePerGas and maxPriorityFeePerGas requires type: "0x2"

**Comment by iObedson** [comment]
I'm having similar issue!

Invalid transaction envelope type: specified type "0x0" but including maxFeePerGas and maxPriorityFeePerGas requires type: "0x2"

![Metamask error](https://user-images.githubusercontent.com/86617200/129362934-175bd223-64d4-445f-a162-ab1c2b871545.png)

**Comment by citizen-lab** [comment]
I also had this issue and would like to know how to resolve it. I missed a mint today, and would like to not miss any more in the future because of this error.

**Comment by danjm** [comment]
@VexyCats @lydianblues @iObedson @citizen-lab Would any of you be able to share the dapps you are intereacting with when this happens?

If you prefer, you can share privately by creating an issue with our customer support: https://metamask.zendesk.com/hc/en-us/requests/new

If we can investigate one of these dapps, we will be able to diagnose the issue

**Comment by danjm** [comment]
> Send an eth transaction with a gas limit of say "30000", normal web3 sendTransaction with a value.

Oh, maybe this implies that it can happen with any dapp that does that...

**Comment by danjm** [comment]
If you are experiencing this during local development, can you share the transaction parameters of the transaction that is causing this issue?

**Comment by hariesnurikhwan** [comment]
@danjm this happened for my production dapp as well, but it seems, this doesn't happen to everyone because some of our users were able interact with our contract using eip 1559 tx.

**Comment by danjm** [comment]
@hariesnurikhwan Which dapp is that?

**Comment by iObedson** [comment]
Ok, my case was a clone of Dapp University decentragram

**Comment by nijuusanji** [comment]
I uninstalled metamask version 10.0.1 then install metamask version 9.8.4  and it works! (chrome and firefox)

**Comment by danjm** [comment]
@iObedson Thanks for sharing the dapp you are using.

I am pretty sure what is happening here is that web3.js is automatically adding a `type` property to transactions that don't specifiy a type or gas fee parameters. This defaults to type `0x0`. (https://github.com/ChainSafe/web3.js/commit/c474f8fcfb525c9d82f6f71b6f2073b6ec94be5c#diff-9050e060908a6957eb4e25bb2f4b8930f5097e55e846e0e8194ff5fa3a3440a4R835)

Then metamask is adding eip1559 gas fee properties, but these require type `0x2`. https://github.com/MetaMask/metamask-extension/blob/develop/app/scripts/controllers/transactions/index.js#L408-L449

MetaMask should respect a type property if no other gas fee parameters are provided, and autoadd properties that align with a type. A fix to this will be made very soon.

In the meantime, dapp developers looking to work around this issue can try the following if developing for EIP1559 compatible networks (mainnet, rinkeby, ropsten, goerli): add `type: '0x2'` to the parameters you pass to `send` or `sendTransaction`. If you are developing a dapp that you aim to be compatible on both EIP1559 networks AND on non EIP1559 networks, you will need to set the type depending on whether the current network is EIP1559 compatible or not. I can comment more on that if someone needs help.

However, once MetaMask makes the fix I mention above, the error should go away. Note that because of the way web3.js currently works, your users might default to using non-EIP1559 gas properties (i.e. `gasPrice`) even when on an EIP-1559 network,

**Comment by sohaibgv** [comment]
@danjm How does this work for methods that are not transactions?
I'm getting the same errors for contract interactions such as unstake and stake. But the contracts only allow one parameter (amount) to be sent along. Passing type wouldn't really work.
I've been looking into workarounds like using sendTransaction to call a contract method but unsure of what this would work. Found the following but would like some recommendations on the best work around.
https://ethereum.stackexchange.com/questions/8736/how-to-call-my-contracts-function-using-sendtransaction

**Comment by sohaibgv** [comment]
Question seems to have been solved by myself. You can just simply pass it into the .send() parameter when calling the function like this:
(React class based)
`this.state.tokenFarm.methods.unstake(this.state.stakingBalance).send({ from: this.state.account, type:'0x2' })`
Hopefully we can all work around this issue for now.

**Comment by hariesnurikhwan** [comment]
@danjm How do I make my dapp compatible for both?

**Comment by danjm** [comment]
@hariesnurikhwan You need detect whether the current network is EIP1559 compatible or not. To do so, you can make a call to get the latest block, and check if the block data has a `baseFeePerGas` property. You should be able to use this to get the block: https://web3js.readthedocs.io/en/v1.4.0/web3-eth.html#getblock

If it has a `baseFeePerGas` property, you know it is an EIP1559 network and set the type to `0x2`, and if it does not, you can leave the type empty

**Comment by GregTheGreek** [comment]
We (web3js) are getting a patch put together. This was an oversight on our end due to complicated legacy code and tests. Sorry for any inconveniences. 

To mitigate this in the future we’ve been working on a ground up rewrite natively in TypeScript and it’s nearing a beta release. Hopefully in the future it will be much more maintainable.

**Comment by iObedson** [comment]
> I uninstalled metamask version 10.0.1 then install metamask version 9.8.4 and it works! (chrome and firefox)

yes! for none techie this actually solve the problem. Thanks @nijuusanji

> I uninstalled metamask version 10.0.1 then install metamask version 9.8.4 and it works! (chrome and firefox)

**Comment by GregTheGreek** [comment]
👋

We've published a new release can you please test it out. 

We've ran it across multiple repos and the error reported above. It seems to have been fixed. 

https://github.com/ChainSafe/web3.js/releases/tag/v1.5.2-rc.0

**Comment by spacesailor24** [comment]
> Ok, my case was a clone of Dapp University decentragram https://github.com/dappuniversity/decentragram

I've tested this Dapp using `web3@1.5.2-rc.0` and no longer received the error

**Comment by danjm** [comment]
thanks @GregTheGreek!

**Comment by JF0001** [comment]
I have added the type: '0x2' to the list of parameters passed in my send function, but I am still receiving the error. I am using MetaMask Version 10.0.2 with web3 Version 1.2.9, developing on the Ropsten Network.

**Comment by tylerimpey** [comment]
Also still having this issue, tried downloading the recommended version of web3 and didn't fix. Passing 0x2 as the type seems to be the only way but then I receive an "Unknown processing time" notification from MetaMask, where it seems to think the transaction will take an extended amount of time.

**Comment by mustafamertkisa** [comment]
You can try this:

metamask settings -> advanced -> reset account

**Comment by NealWalters** [comment]
How can we find a safe source for the old 9.8.4 release.  I'm trying to unlock 1 ETH from Plasm (now Astar), and getting the above error?  Is this site safe? https://www.crx4chrome.com/crx/252440/   I'd like to install the old release, do my transaction, then go back to the current release. 

Thanks,
Neal

**Comment by cbrzn** [comment]
hey it seems that you support tx type `0x2` but not `0x02`, hence, not making you compatible with `ethers-rs` library - this issue is related https://github.com/foundry-rs/foundry/issues/3890

fwiw, I think you it would make sense if you also support `0x02` as transaction type since that's how the EIP defines it (iiuc) https://eips.ethereum.org/EIPS/eip-1559#abstract

**Comment by danjm** [comment]
The initially raised issue was resolved in 2021, but the comment from 2 days describes a bug that was never sovled. I have opened a new ticket for the latter https://github.com/MetaMask/metamask-extension/issues/18076
