### ISSUE TITLE
Method "wallet_watchAsset" does't work correctly

### ISSUE THREAD

**Issue by Cast0001** [MetaMask/metamask-extension#12416]
Hi,

**Describe the bug**
1. In the **FireFox** browser, I see the problem that this method does not handle the promise. It always hangs in the pending status, even after the user selects one of the options. It is impossible to understand what the user has chosen. If you call the method again, the window for adding a token will no longer open.

2. In the **Chrome** browser, the problem is that immediately after calling the method, an object is returned. Although a boolean value should be returned depending on the user's choice, the object is returned immediately before  the user chooses. Because of this, there is no way to hang up the loader and find out what the user has chosen.

**Steps to reproduce**
1. Open Firefox / Chrome
2. Go to a page with ethereum connected
3. Paste this code in the console:
```
ethereum.request({
  method: 'wallet_watchAsset',
  params: {
    type: 'ERC20',
    options: {
      address: '0xb60e8dd61c5d32be8058bb8eb970870f07233155',
      symbol: 'FOO',
      decimals: 18,
      image: 'https://foo.io/token-image.svg',
    },
  },
})
  .then(
    (result) => console.log('then', result),
    (err) => console.log('catch', err)
  )
```

**Expected behavior**
Different browsers should have the same behavior. The method should return a Promise with a boolean value after the user has added or has not added a token to the MetaMask.

**Screenshots**
Chrome: https://prnt.sc/1wunm6y (No tokens have been added, but the promise has already resolved)
FireFox: https://prnt.sc/1wunwk3 (Tokens added, but the promise is in pending status)

**Browser details (please complete the following information):**
 - OS: macOS
 - Firefox: 93.0 / MetaMask: 10.2.2
 - Chrome: 94.0.4606.81 / MetaMask: 10.2.2

**Comment by danjm** [comment]
Acceptance criteria for the chrome issue:

- The method should return a promise that resolves once the user clicks confirm in the popup

**Comment by JDinesenEmoney** [comment]
Any news on this error? (the second part - chrome not resolving the promise as expected)

I ran into this error trying to add multiple tokens in a while loop. At first, all of the added tokens are displayed in the UI for the user to accept, even if we "await" for user response in each loop. However, if the user accepts, only the latest token is added and the rest is queued up, requiring opening the extension and accepting multiple times.

```
for (const key of Object.keys(currencies)) {
        await window.ethereum.request({
          method: "wallet_watchAsset",
          params:
            {
              "type": "ERC20",
              "options": {
                "address": currencies[key],
                "symbol": key,
                "decimals": 6,
              }
            }
        }).then((result: any) => {
          console.log(result)
        })
    }

```
We need the promises to actually resolve based on users accepting or rejecting.

A function to add multiple assets would be much appreciated, but i guess thats for another issue.

Thanks in advance :)

**Comment by danjm** [comment]
We should have a better understanding of this error by early next week. And maybe a fix merged by the end of next week. So a solution might be in prod in 2.5 weeks. I will comment here if that timeline changes.

**Comment by danjm** [comment]
Findings so far:
- the `watchAsset` method in token controller returns an object that contains a promise (named `result`) https://github.com/MetaMask/controllers/blob/main/src/assets/TokensController.ts#L393
- the `watch-asset.js` handler in `app/scripts/lib/rpc-method-middleware` awaits a promise returned by `watchAsset` (named as `handleWatchAssetRequest` in that file)
- on chrome, the behaviour reflects what the code seems to be intended to do: immediately resolves the await for `watchAsset` with an object containing the `result` promise, but the result promise is logged as an empty object (perhaps due to serialisation in message passing between the extension and dapp context)
- but on firefox, the only thing returned is a promise that does not resolve. We need to figure out why this is. There might again be a serialization issue where firefox is trying to handle the `res.result` as a promise while chrome is not

Next steps:
- set up a development build on firefox
- put breakpoints in `watch-asset.js` to verify whether or not the code gets past `handleWatchAssetRequest(asset, type)`
- if the code does pass that await, then we need to check the underlying code responsible for handling request responses to see if the code is hanging elsewhere

**Comment by digiwand** [comment]
Hi @shanejonas, glad you are hopping on this. I have jumped to another issue while I was investigating this. Here are my findings. Sorry, I should have posted this here earlier if it helps someone. 

What I have observed is that within the createStreamMiddleware.js, the `processMessage` method calls `processResponse` which calls:
```
    // run callback on empty stack,
    // prevent internal stream-handler from catching errors
    setTimeout(context.end);
```
`context.end` is the callback that triggers `resolve([error, true]);`  in JsonRpcEngine.js.

`processMessage` **does not seem to be triggering in Firefox**. I believe this is the callback discrepancy mentioned above. 

In Chrome, `doWrite` in \_stream_writable_.js is called before `processMessage` in createStreamMiddleware.js. 

`_write` called from \_stream_writable_.js is interesting because it appears `_write` can be called by either:
- node_modules/@metamask/post-message-stream/dist/BasePostMessageStream.js
- node_modules/@metamask/object-multiplex/dist/ObjectMultiplex.js (I have not seen `_write` called here in Firefox)
- node_modules/@metamask/obj-multiplex/dist/index
- possibly other files

I believe where I got stuck figuring out why the `processMessage` was not called in Firefox. Is this an issue with one of the streams? 

Happy to hop on any pair programming sessions for this issue.

**Comment by htmnk** [comment]
Is this #14545 supposed to fix these? 

> In the FireFox browser, I see the problem that this method does not handle the promise. It always hangs in the pending status, even after the user selects one of the options. It is impossible to understand what the user has chosen. If you call the method again, the window for adding a token will no longer open.

> In the Chrome browser, the problem is that immediately after calling the method, an object is returned. Although a boolean value should be returned depending on the user's choice, the object is returned immediately before the user chooses. Because of this, there is no way to hang up the loader and find out what the user has chosen.

I'm still getting an immediately resolved promise when calling `wallet_watchAsset` on chrome and never resolving on firefox. 

Version:
`10.14.6` MetaMask Chrome
`10.12.4` MetaMask Firefox
 `12.3.1` MacOS Monterey

**Comment by digiwand** [comment]
Hi @htmnk, thank you for reporting this! 

The fix has actually been released just 14 days ago with version `10.15.0`. I hope this is working for you now.
https://github.com/MetaMask/metamask-extension/releases/tag/v10.15.0

**Comment by zed-wong** [comment]
> Hi @htmnk, thank you for reporting this!
> 
> The fix has actually been released just 14 days ago with version `10.15.0`. I hope this is working for you now. https://github.com/MetaMask/metamask-extension/releases/tag/v10.15.0

Guys don't forget to update in the firefox store.

**Comment by ch3ll0v3k** [comment]
updated version is not available on firefox addons page, and latest version on /releases section does not contain valid signature, so firefox refuse it to install

**Comment by zed-wong** [comment]
Guys, it's been half of a month, PLEASE update it !!!

**Comment by romain130492** [comment]
any news about that?
im still experiencing the same bug

**Comment by zed-wong** [comment]
> any news about that? im still experiencing the same bug

The lastest version doesn't have this bug.

**Comment by shunz19** [comment]
It seems that this is occouring again in android version of metamask. Anyone with me?
