### ISSUE TITLE
[Bug]: Disabled "Sign" button when signing with EIP-712

### ISSUE THREAD

**Issue by anxolin** [MetaMask/metamask-extension#16415]
### Describe the bug

More than a bug, is a UX issue, but I believe affects to most users judging by the periodic feedback we get from our users.

Metamask support [EIP-712](https://eips.ethereum.org/EIPS/eip-712) that allows to users to sign structured data. 

This is used by protocols that allow gass-less experiences, like [CoW Swap](https://swap.cow.fi), or to improve the UX when doing gas-less approvals of tokens with [eip-2612](https://eips.ethereum.org/EIPS/eip-2612) (in Uniswap for example). This is used a lot also, in web3 logins, and any kind of subsidised transaction flows. The point is, is a very important user flow used by most of the Metamask users, so it would deserve to have a good user experience.

What we have observed is, **the users get stuck in front of the structured data presentation, and they see a disabled button**. Some of them, after a while they notice, there's a little arrow icon floating, and if they click it, then the button becomes enabled. Unfortunately many users don't notice this. 

<img width="357" alt="image" src="https://user-images.githubusercontent.com/2352112/200543427-1ad700a3-0f34-47fe-8549-a3ebf1423f24.png">

We believe, making users click on this arrow, or scroll down the message before enabling the button, is not a good user experience, and is preventing them from using some Dapps. 

### Steps to reproduce

1. Go to  [CoW Swap](https://swap.cow.fi)
2. Select any token pair, input an amount
3. Approve the token for trading (this is a regular transaction, not a meta-transaction)
4. Press on "Swap" 
5. Observe the Metamask popup

### Error messages or log output

```shell
No errors, just a disabled button
```

### Version

All

### Browser

Chrome, Firefox, Microsoft Edge, Brave, Other (please elaborate in the "Additional Context" section)

### Operating system

Windows, MacOS, Linux, Other (please elaborate in the "Additional Context" section)

**Comment by anxolin** [comment]
That's great! I really love the new UI. @bschorchit I cannot agree  more with your goal of making sure users understand what they sign. I actually have some ideas on how to [improve it further](https://www.notion.so/cownation/Metamask-Nicer-meta-info-1c3f97f1f67a4b87b12a4e4b419682ab). 

I think we can do a simpler experiment with CoW Swap (since the message to sign is very simple, but yet it's hard for users to verify what they sign.


Anyways, my above proposal is for a different problem. What I exposed above, has to do with some users getting stuck without knowing what to do. it's not obvious to them they need to scroll.
One idea would be to change the label of the button to indicate they need to scroll all they way down in order to sign.

**Comment by MindyCoW** [comment]
The UX problem here is that users can't sign the order until they specifically click the arrow. What I see in the majority of my usability test sessions is this: 

1. Metamask window opens
2. User scrolls all the way down to the bottom of the message
3. Sign button remains passive
4. User at best experiences confusion and frustration until they realize they have to click the arrow; at worst they think the button is bugged and give up

To be clear: requiring the user to scroll down is fine. Most users do this anyway. But requiring them to click the "down arrow" when they're _already_ as far "down" as they can go is counterintuitive.

**Comment by anxolin** [comment]
Any news on the issue?

**Comment by MindyCoW** [comment]
I believe this issue has been fixed, no?

**Comment by anxolin** [comment]
@MindyCoW I don't believe so. 
Metamask improved its support for EIP-712, but this aspect has not been addressed unfortunately.


<img width="392" alt="image" src="https://github.com/MetaMask/metamask-extension/assets/2352112/09e1a205-b116-445b-a510-23534b553675">

**Comment by anxolin** [comment]
A bit of a side topic, but since I mentioned above about the noticeable EIP-712 improvements, I just want to highlight, there is still a lot of improvement is missing to be on pair with https://rabby.io, which is now my wallet of choice :) 

The sell amount and buy amount are still not formatted nicely into some token amount, so users continue to sign blindly hoping these amounts match what the UI says. 

Same for ValidTo. It should be a deadline presented as a date.

Come on, Metamask. Just try how Rabby wallet or Brave Wallet presents CoW Swap. These UX feature actually protect your users. I have a lot of love and respect for Metamask, but these things made change to Rabby. I need protection from my wallet.

**Comment by MindyCoW** [comment]
In my eyes, the UX issue was requiring the user to _click on the arrow_ rather than simply scrolling down in order to activate the Sign button. At least for me, that issue seems to have been fixed.

**Comment by bschorchit** [comment]
Closing as this is no longer an issue in the latest release (v12.2). We're considering entirely removing the requirement to scroll to bottom in the new confirmations soon.
