### ISSUE TITLE
[Bug]: User is able to send and (possibly) confirm transactions that involve 0 NFTs (ERC1155)

### ISSUE THREAD

**Issue by sleepytanya** [MetaMask/metamask-extension#23801]
### Describe the bug

You can send and confirm transactions that involve 0 NFTs (I haven't tried to confirm the transaction but 'Confirm' button is active). In such transactions, the 'Total' field will display the NFT's name along with applicable fees. The 'Estimated changes' field does not display the NFT's name.
Current Send flow doesn't let user send 0 NFT.

### Expected behavior

-

### Screenshots/Recordings

Multichain:

https://github.com/MetaMask/metamask-extension/assets/104780023/2d26cdfb-4a96-4fe8-a36c-160001b19ebb
 
NFT Send flow on production:

https://github.com/MetaMask/metamask-extension/assets/104780023/151d9552-f2ac-450b-a6fd-69e68903c665

### Steps to reproduce

1. Go to NFT tab.
2. Click on any NFT to start Send transaction
3. Choose the recipient's address
4. You can send 0 NFT

### Version

Dev build develop branch

### Build type

None

### Browser

Chrome

### Operating system

MacOS

**Comment by sleepytanya** [comment]
Dev build `mb843/data-flows`, Chrome
Still able to send 0 NFT:

https://github.com/MetaMask/metamask-extension/assets/104780023/d7754c99-0166-470e-b38f-d7ba3ca82ee1

**Comment by sleepytanya** [comment]
Still present on [the latest build](https://consensys.slack.com/archives/C068SFX90PN/p1712847894604369?thread_ts=1712701228.770469&cid=C068SFX90PN):


https://github.com/MetaMask/metamask-extension/assets/104780023/a2f245db-7a95-40fd-be78-8771dedd87ec

**Comment by ejwessel** [comment]
This looks like it's by design. When transferring tokens a user is allowed to transfer 0 if they so desire. 
However, I agree though that his could be confusing from an ERC1155 perspective.

**Comment by ejwessel** [comment]
Comparing V11.13.1 to develop, this looks to be a regression.

**Comment by BZahory** [comment]
No longer present on latest swap+send build; removing tag

https://github.com/MetaMask/metamask-extension/assets/44588480/f4c711ee-acab-4471-9b26-e52087b07df6

**Comment by hesterbruikman** [comment]
For hygiene, does this mean we can close this ticket once Swap and Send is merged?

**Comment by sleepytanya** [comment]
Fixed - user can't send 0 NFT:



https://github.com/MetaMask/metamask-extension/assets/104780023/c146c113-74df-46ec-aa27-c48b669694d2

**Comment by sleepytanya** [comment]
Present on RC 11.17.0

 https://jam.dev/c/9348ba95-208a-4545-903d-6fd16831df1c 

 and on production 11.15.4

 https://jam.dev/c/db00270a-fa7c-4d35-93d8-febf89547952

**Comment by MarketBeatAd** [comment]
Hey I created the USDT USDA and the usdc I was at the Clark house apartments when I was in the ftx hackathon. So I not going to steal . Do your homework before you excuse

**Comment by benjisclowder** [comment]
Should this issue remain open, @sleepytanya ? I see it is now designed to show prompt that you cannot send 0 of this asset. 

![Image](https://github.com/user-attachments/assets/a01554ab-9959-4bef-9e22-02c79b443a24)

**Comment by sleepytanya** [comment]
Thank you @benjisclowder !

Closing as the issue was fixed and is not present in the RC 12.10.0:



https://github.com/user-attachments/assets/29717c8c-3462-4c09-9dad-094dedfa1d6f
