### ISSUE TITLE
Add "always test your seed phrase" tip somewhere

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/metamask-extension#3331]
If you're going to use an account for value, make sure that seed phrase works.

Inspired by https://github.com/MetaMask/metamask-extension/issues/3191#issuecomment-368743316

Add to Terms? Its own notice? The seed page?

**Comment by lazaridiscom** [comment]
Ok, @danfinlay, I would suggest here to go a few steps further:

* Implement a **Seed Phrase Check** (SPC)
* This SPC  is applied to any new account

* with the Next Update: existent accounts are verified by the SPC (without log-out, if technically applicable)

* The check can then detect those rare cases where something is wrong.

if you hit on this:

=> Your seedphrase does not belong to this account, check another one?

Once the loop is  exhausted:

=> You should move your ETH to a new newly created account. This process has 4 automated steps:

- we create a new account
- we verify the new Seedphrase
- you ensure that you create safe copies of your Seedphrase
- we transfer your ETH to the new account
- we delete your old account

-

(The above is a draft, I hope it gets clear. If I understood the problems wrong, just ignore.)

**Comment by lazaridiscom** [comment]
And **if** I understood right, this issue is a highest severity one (loosing funds is highest severity)

**Comment by danfinlay** [comment]
I think this SPC concept is unlikely to help the problem:

The issue involves situations where a user is shown one seed phrase, and then a different one is saved and used for generating accounts.

If that's the case, every account *is successfully generated from the persisted seed phrase*, and so MetaMask is unable to detect that the user backed up the wrong phrase.

That said, it wouldn't hurt to add extra analytics like this, and so it's probably worth doing just as *something to try*.

Also, if this bug does exist, it is very possibly fixed by the new UI that we've just begun rolling out, since it completely changes the way we first show & confirm the seed phrase.
https://medium.com/metamask/metamasks-new-ui-has-begun-to-roll-out-74dba32cc7f7

**Comment by lazaridiscom** [comment]
> The issue involves situations where a user is shown one seed phrase, and then a different one is saved and used for generating accounts.

I've read several of the issues, and it seems that there are different cases. But the thing is: If an account is active, and the user has the wrong seed (for any reasons, be it MM fault or users fault), then a post-creation SPC could save him the trouble to loose funds.

For new accounts, a mandatory SPC would help to reduce problems.

Still not 100% clear, but I feel the SPC is a **must** functionality.

(Seed Phrase Verification = SPV, great, started already renaming...)

**Comment by danfinlay** [comment]
@lazaridiscom I've opened that as its own issue, so it can be explored there, and maybe get its own bounty.

**Comment by scsaba** [comment]
> Also, if this bug does exist, it is very possibly fixed by the new UI that we've just begun rolling out, since it completely changes the way we first show & confirm the seed phrase.

I think the 'confirm seed phrase' page used on the new UI is a good step into the right direction, but probably it should not show the seed words for the user and ask the user to select them in the right order. It can hide some possible user errors, e.g. backing up the seed phrase in a wrong format. In my opinion, the confirmation process should be exactly the same as the restoration. Just an empty textbox where the user needs to input (enter or copy-paste) the seed. This would be a more foolproof, would ensure more that the user has the correct seed phrase in the correct format.

This + the automatic seed verification script after first account creation and after each login might cover/reveal most of the possible failures.

**Comment by Gudahtt** [comment]
@danfinlay @rachelcope Does this idea still have merit? Or are we already suggesting that the user test their seed phrase in any current designs? :thinking: 

I don't recall this exact suggestion being there. I'm torn on whether this is something we should emphasize. Maybe improving our onboarding confirmation page to do a better job of confirming the seed phrase is sufficient, rather than asking the user to go out of their way in a manner we're not assisting with. The "back up your seed phrase" instruction is so important that I'd rather not crowd it out with other instructions either.

**Comment by rachelcope** [comment]
I don't think this is still relevant. Confirming the seed phrase should be sufficient for users to confirm that they correctly saved their seed phrase. In addition, the new video and updates to the seed phrase onboarding views will help users better understanding what a seed phrase is and how/why to keep it safe.

**Comment by Gudahtt** [comment]
OK! At the very least, if the confirmation page _isn't_ sufficient it should be improved until it is. That would make more sense then asking users to perform a tedious manual step without any help. I'll close this for now then.
