### ISSUE TITLE
[Bug]: Critical - Provider data stale/bad when connected network differs from activity filter network

### ISSUE THREAD

**Issue by johnnyshankman** [MetaMask/metamask-extension#36532]
**Describe the bug**

MetaMask's provider behaves as if the blockchain is frozen at a specific block number when the network connected to the website differs from the network selected in the activity filter dropdown. The `eth_blockNumber` RPC method returns a static block number that never advances, and all blockchain data remains stale as though no new blocks are being produced.

This occurs regardless of which networks are involved (L1 or L2) and which RPCs they rely on. For example:
  - Connecting a website to Ethereum mainnet, then changing the activity filter to Optimism causes the issue on mainnet
  - Connecting a website to an L2 like Optimism, then changing the activity filter to any other network causes the issue on that L2

**This causes severe issues where all provider information is outdated, and increases the risk of unknowingly submitting bad transactions that will revert due to stale data. Also increases the likelihood of displaying incorrect information on the page.**

**Expected behavior**

The network selected in the activity filter (used only for filtering transaction history) should not affect the provider's behavior on the network actually connected to the website. The `eth_blockNumber` method should return current block numbers for the connected network, and all blockchain state should reflect the actual current state of that network, regardless of which network is selected in the activity filter dropdown.

**Screenshots/Recordings**

#### Setup

<img width="403" height="633" alt="Image" src="https://github.com/user-attachments/assets/29bc9ae3-7569-4160-bc5c-86a2d37646d2" />

####  On OpenSea (includes timestamps and current net)

<img width="1013" height="1312" alt="Image" src="https://github.com/user-attachments/assets/a885412a-16e2-427f-b13f-1cfdc88f2b88" />

#### On Etherscan (includes timestamps and current net)

<img width="1019" height="726" alt="Image" src="https://github.com/user-attachments/assets/c959a0b6-0035-4cfb-8ce5-69a3e46c91d9" />

**Steps to reproduce**

1. Install MetaMask extension version 13.0.0
2. Navigate to a dApp website (e.g., Etherscan, OpenSea)
3. Connect MetaMask wallet to the site
4. Note which network is connected to the website (shown in the "Manage permissions" area)
5. Click the network selector dropdown in the activity section (below the main balance area)
6. Select a DIFFERENT network than the one connected to the website
7. Open browser console
8. Run: `Number(await window.ethereum.request({method: "eth_blockNumber"}))`
9. Wait 1-2 minutes
10. Run the same command again
11. Observe that the block number has not changed despite new blocks being produced on the connected network
12. Change the activity filter back to match the connected network and observe blocks now advance normally

**Error messages or log output**

```shell
None
```

**Detection stage**

In production (default)

**Version**

13.3.2

**Build type**

None

**Browser**

Chrome

**Operating system**

MacOS

**Additional context**

This issue occurs whenever there is a mismatch between:
1. The network actually connected to the website (shown in "Manage permissions")
2. The network selected in the activity filter dropdown (used to filter transaction history)

The problem affects all blockchain data accessed through the provider, not just block numbers - the entire provider state appears frozen at a specific block.

Other wallet providers (Rainbow, Coinbase Wallet) do not have this issue as they typically don't have separate network selectors for website connection vs. activity filtering.

The root cause appears to be that the activity filter network selection is incorrectly affecting the provider's RPC behavior for the actually connected network.

**Comment by johnnyshankman** [comment]
Bumping this. 

We, dApp developers, are getting flooded with bug reports that directly trace back to this issue which is not solvable by the dApp. Very frustrating for things like auctions and limited time windows for purchases as the blocktime never advances. Users think there is still supply left, or still time left in the auction, or think they are the top bidder -- but all of those are incorrect according to the latest block which is not being fed through the provider.

This is an ecosystem-wide issue now. I've made OpenSea and Etherscan teams aware.

**Comment by johnnyshankman** [comment]
This is still an issue and my Metamask has autoupdated to 13.4.0

<img width="1012" height="1294" alt="Image" src="https://github.com/user-attachments/assets/6202a956-c1cb-4272-96e8-f6297d8edcfc" />

@jiexi @dylanbutler1 please do not close correct issues that are not solved, what the heck?

**Comment by johnnyshankman** [comment]
Also why was this marked as INVALID-ISSUE-TEMPLATE with no explanation? I followed the template... 

It's very frustrating that only bots are responding/interacting with this issue. I'd appreciate if a human took a look at this!

**Comment by jiexi** [comment]
Sorry, @johnnyshankman. I'm not sure why the Jira <-> Github bot closed this issue. This is currently in the process of being resolved. A fix has already been identified and is being implemented.

https://github.com/MetaMask/eth-block-tracker/pull/340
https://github.com/MetaMask/eth-json-rpc-middleware/pull/416

One more PR will be needed after this to bump the `eth-json-rpc-middleware` package in the Extension client. 

Thank you for your patience.

**Comment by jiexi** [comment]
Also thank you for taking the time to report this. Apologies for the lack of communication! 🙏

**Comment by johnnyshankman** [comment]
@jiexi ah you're the best, thank you! appreciate you!

**Comment by jiexi** [comment]
Sorry, I lied. One more PR before the one for Extension.

https://github.com/MetaMask/core/pull/6811

**Comment by Unik0rnMaggie** [comment]
Reproduced on v13.5.0 RC, the fix should be cherry-picked into RC v13.5.0

**Comment by johnnyshankman** [comment]
Thanks for following up today. Yep I'm also still experiencing in 13.5.0 as well.

**Comment by jiexi** [comment]
Update. My initial fix was slightly suboptimal. @Gudahtt has a better fix [here](https://github.com/MetaMask/eth-block-tracker/pull/344). Sorry for the hiccup. Thank you so much again for your patience and understanding 🙇

**Comment by johnnyshankman** [comment]
No problem @jiexi appreciate ya getting an optimal solve out in the wild. Let me know when it's live!

**Comment by johnnyshankman** [comment]
Just circling back can confirming issue existed in 13.4.2 as well, in Arc my MM even after managing the extension and requesting an update persists at 13.4.2. Figured this is worth noting. @jiexi

**Comment by jiexi** [comment]
Thank you for that additional information 🙏 

Here's the [Extension PR](https://github.com/MetaMask/metamask-extension/pull/36869). I think we're going to cherrypick this fix into the next release given the severity

**Comment by Gudahtt** [comment]
Fixed in #36869, which we'll be including in v13.5.0

**Comment by Gudahtt** [comment]
Thanks again for your excellent report @johnnyshankman ! Once v13.5.0 is out (probably next week?), let us know if you notice this is still not working properly, and we can re-open this to investigate again. Pretty sure it will be fixed though.

**Comment by johnnyshankman** [comment]
@Gudahtt incredible. thank you for the concerted effort on this. when 13.5.0 comes out ill upgrade and retest.

**Comment by johnnyshankman** [comment]
Can confirm still present in 13.4.3 which released and auto-updated in my MM today 👍🏼

**Comment by johnnyshankman** [comment]
@jiexi any timeline on release this week?

cc @Gudahtt

**Comment by johnnyshankman** [comment]
bump @jiexi @Gudahtt

manifold is still getting tons of issues reported due to this bug and we would love to see this out ASAP as it's been almost 3 weeks.

thank you ahead of time!

**Comment by Gudahtt** [comment]
We've had to halt the rollout of v13.5.0 unfortunately. Some other changes in this release were unexpectedly disruptive to users with _a lot_ of accounts, so we're going to mitigate that before continuing. Halting a release for an extended period is a rare occurrence that is extremely inconvenient and disruptive for us, so trust me we didn't make this decision lightly. Bad timing I know.

It is at 1% rollout on Chrome, so you _can_ test it out by manually updating. The steps for that are basically:

* navigate to `chrome://extensions`
* enable Dev mode
* click the "Update" button next to the MetaMask extension
* Turn off Dev mode (don't forget this step! Dev mode disables important security features)

You might also encounter a crash when you first open the popup, due to a Chromium bug that is fixed but not released yet (due to be published to stable in December). Workaround is to toggle the extension off then on again.

A new installation would also get the updated version, alternatively.

That will let you test the fix here at least. We'll still need to wait before the majority of users can benefit from the fix. We'll have it rolled out as quickly as we can, sorry for the unexpected delay here.

**Comment by johnnyshankman** [comment]
Oof okay, keep me posted. We've had a few high profile artists reporting issues that are directly related to this and we're getting kind of frustrated trying to explain this to the average user over and over again. Collectors of stuff on Ethereum are not savvy enough to understand how to circumvent this issue or identify it so we're just stuck with needless bug reports piling up and users pointing the finger at us when it's not something we can control at all.

**Comment by johnnyshankman** [comment]
Fixed in 13.5.0 can confirm @jiexi @Gudahtt ! Had to manually update but works great.

**Comment by Gudahtt** [comment]
Some good news to share. While v13.5.0 rollout remains halted, the problems it caused have been mitigated in v13.6.0, which is on-schedule and expected to begin rollout to 1% on Monday morning. It should be at 100% roughly mid-week if all goes well.

**Comment by Gudahtt** [comment]
The fix should be 100% rolled out now as part of v13.6.0. Users will get it when they next restart their browser. You can advise users who encounter this error to restart their browser to get the update.
