### ISSUE TITLE
Since 4.5.0 Metamask does not submit or reject transactions on many previous working sites.

### ISSUE THREAD

**Issue by radamosch** [MetaMask/metamask-extension#3898]
Build 4.4.0 works fine , after this it is broken -was tearing my sites apart trying to figure out why.
Use with web3 version 0.20.6 on ropsten at least.

This has been like this 9 days.

Can you please explain what is going on and what it will take to make sites now compatible with this new 4.5.x version of MM - or if it's a bug can it be fixed?

![image](https://user-images.githubusercontent.com/35626984/38382683-82971f74-3902-11e8-9e12-9bba8a5c8dbe.png)

Thank you
Rada

**Comment by radamosch** [comment]
Ok, for developers who are working with this - I got it working , but I think MM needs to be fixed because there are many sites in the wild this affects.

a) I switched to web3@0.20.0
b) remove any gasLimit / gasPrice / gas override in the transaction set up code.
c) if using react - don't use static functions (this may not have affected much - but it worked for me).

MM still needs to fix IMO

**Comment by radamosch** [comment]
Try removing any gas or gas limit overrides.

**Comment by robertmagier** [comment]
Thank you very much. It worked.

**Comment by auser** [comment]
I get this error too, but it just hangs with loading (metamask vs. web3).

![](https://d.pr/i/aMNwyx.png)

**Comment by robertmagier** [comment]
I had exactly same problem, but it was fixed after I got rid of gas limit.

**Comment by robertmagier** [comment]
Did you try to reset your account ?
It will remove transaction history but will also let you to calculate nonce
again. Maybe this is the problem.

**Comment by brandoncurtis** [comment]
I tried the account reset button to no avail... The busy wheel would spin
forever when trying to send, and then the TX would appear without a nonce
next to it (and wouldn't make it into my node's memory pool). 4.4.0 is
working fine for me now.

**Comment by robertmagier** [comment]
I understand. I was able to use 4.5.0. But I also uninstalled and installed
it after I had problems. Clearly you need help from someone smarter than me.

**Comment by bdresser** [comment]
hey folks - as @kumavis mentioned, we rolled back an update to how we handle txParams that may have caused this. 

is anyone still experiencing this issue on 4.7.4?

**Comment by bdresser** [comment]
closing due to inactivity~
