### ISSUE TITLE
metamask in brave doesn't render (always blank)

### ISSUE THREAD

**Issue by cryprohippo** [MetaMask/metamask-extension#4281]
Hi, 

expected behaviour - metamask opens and prompts for login. 

actual behaviour - 
My metamask extension in brave browser has not worked for a month or two. 
When I click on the extension icon, the popup window opens, but is completely blank. It doesn't matter how many times I click on it. Occasionally it is transparent instead of blank. If transparent, it will be blank (white) if I click on it again. 
I have noticed a new behaviour (which may have started after windows updates this week, but not certain) but the popup window borders vibrate rapidly - scrollbars on right and bottom, and the left border. Top doesn't have a vibrating border

I've disabled and re-enabled the extension, and reinstalled brave. No change. 

![image](https://user-images.githubusercontent.com/39367868/40165888-14ab991c-59b5-11e8-8942-3bdc4a81f33a.png)

browser - brave (extension works fine in chrome)

os - win 10 x64 v1803 build 17134.48 (although issue predates this build). 

Thanks

**Comment by RubenOlt** [comment]
Hi. I have the same issue. However if I reload a few times the normal screen appears.

**Comment by z12b** [comment]
Same issue. I tried installing the version before this latest issue and I had the same issue. Please tell me I didn't overwrite the vault data for metamask as I lost my 12 digit key :/

**Comment by danfinlay** [comment]
If you reinstalled you really may have overwritten your vault. Your recourse then would be "do you have backups from before you reinstalled?"

It's very important to back up your seed phrase.

**Comment by tcivil412** [comment]
Is there a time frame as to when it will work again on Brave?

**Comment by cryprohippo** [comment]
or is there a recommended procedure to return everything to default? I can't see any way to uninstall the extension in brave, as it  is built in.

**Comment by danfinlay** [comment]
We currently have two different bugs that may be causing this with Brave: #4330 and #4270.

We will be working on both of them soon.

If you need to use MetaMask in the meanwhile, please use your seed phrase to restore your accounts on another browser for now.

If you do not have your seed phrase backed up, do not uninstall MetaMask from your Brave browser, it should fix itself with an auto update once we resolve the issue, and you will be able to export your seed phrase then. It is also best to regularly back up your computer in this case, so that if you have a hard drive failure, you can still recover the vault from the backup.

I am now closing this issue as a duplicate of those more specific issues.

**Comment by cryprohippo** [comment]
Hi, 

This issue is still not resolved. 
I collected an update for brave this morning - 0.23.77
metamask extension is 4.3.0

Is there anything else I need to do? Metamask has been totally non functional for a long time now.

**Comment by chrishobcroft** [comment]
Same here.
