### ISSUE TITLE
DOMException Failed to execute 'postMessage' on 'Window'

### ISSUE THREAD

**Issue by bicep** [MetaMask/metamask-extension#6080]
I'm aware of #1280 (I'm running local server on port 3000) and #5333 (I'm not so sure what this is but it was fixed?). Apologies in advance if this was covered already, I cant seem to find it.

**Describe the bug**

I've set up web3 so that I'm using the latest version of web3 (1.0.0 beta 43) that sets the provider from the metamask's web3.

`const provider = window.web3.currentProvider;
provider.enable();
const web3 = new Web3(provider);`

I've currently deployed a contract on Rinkeby and am trying to get a simple public variable called manager using `contract.methods.manager.call()`, but I'm getting this DOMException in Chrome:

<img width="884" alt="screen shot 2019-01-31 at 12 01 47 am" src="https://user-images.githubusercontent.com/11747211/52022688-ff1b0a00-2534-11e9-9f0b-97c48c9d75fd.png">

**Comment by YukiOta** [comment]
I have a same issue... Any solution for this?

**Comment by phamhieu** [comment]
I fixed this issue by running `npm install`. I'm using **web3:1.0.0-beta.37**

**Comment by chentschel** [comment]
Same issue with web3@beta.41 .Solved installing web3:1.0.0-beta.37

**Comment by YukiOta** [comment]
Solved by installing  **web3:1.0.0-beta.37**

Thank you so much! 
@phamhieu @chentschel

**Comment by WadhahEssam** [comment]
not solved for me by updating web3 to 1.0.0-beta.37
does any one have any solution 
///
by the way the project was working and suddenly this error started to appear, i went to the rewind the project many steps but this error won't go, it drives me crazy

**Comment by serapath** [comment]
Not sure, but i have the same issue https://play.ethereum.org/play-editor/
It seems to work when running on `localhost` during development with a dev server.

Any clue what this is about?

**Comment by ninabreznik** [comment]
Any news about how to resolve this issue?

**Comment by ninabreznik** [comment]
![screenshot_2019-03-03_07-05-05](https://user-images.githubusercontent.com/1076427/53697154-548c4600-3d83-11e9-8c75-3f80268573e1.png)
![screenshot_2019-03-03_07-03-41](https://user-images.githubusercontent.com/1076427/53697155-548c4600-3d83-11e9-9bd9-136e44f4639f.png)

**Comment by szerintedmi** [comment]
Getting the same with beta47 :(

**Comment by ninabreznik** [comment]
I also get this now with another Dapp. First Dapp uses ethers.js and the second one web3.js :(

**Comment by wfoster232** [comment]
Also hitting this issue with **1.0.0-beta.48** when attempting to perform a web3.currentProvider.send({ method: 'personal_sign', params: params, from: _account});

**Comment by Philipid3s** [comment]
Same issue with **1.0.0-beta.48** - solved by installing the **beta.37**

**Comment by nicholaspai** [comment]
also resolved this by switching from beta.48 to beta.37

**Comment by arnigudj** [comment]
sam here, resolved this by switching from beta.48 to beta.37... hoping that this will be resolved in beta.49

**Comment by kumavis** [comment]
Opened an issue on web3.js with live reproduction demo https://github.com/ethereum/web3.js/issues/2528

**Comment by kumavis** [comment]
@wfoster232 this does not look correct, `from` should be encoded in the params
```js
web3.currentProvider.send({ method: 'personal_sign', params: params, from: _account});
```

**Comment by kumavis** [comment]
conclusion from https://github.com/MetaMask/metamask-extension/issues/6262#event-2202563870:

> for `web3@1.0.0-beta.38` the `web3.eth.personal.sign` requires a 3rd parameter, a password string (unused in metamask) 
if you were using a callback before, it accidently includes the callback in the params in place of the password string. the callback is not json serializeable, thus throwing the error.

**Comment by kumavis** [comment]
based on comments above, sounds like there are some additional issues (error on deploy, etc)

**Comment by jamesmorgan** [comment]
Ye I get this using Nuxtjs and metamask - any ideas? Will try to downgrade to `1.0.0-beta.37`

**Comment by nickgeoca** [comment]
Have tried `1.0.0-beta.37` and other versions, even re-cloning and rebuilding the server, but keep getting the same errors.

```js
  try { c = await MyContract.deployed(); } catch (e) {console.log(e);}
```

Firefox error
```
TypeError: "this.provider.sendAsync is undefined"
                   sendAsync contract.js:24
                   sendAsync requestmanager.js:80
                   get property.js:116
                   detectNetwork contract.js:512
                   Promise es6.promise.js:177
                   detectNetwork contract.js:503
                   deployed contract.js:451
                   _callee5$ TokenPollInterface.js:119
```
Chromium error
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': function (err, result) {
if(result && result.id && payload.id !== result.id) return callback(new Error(...<omitted>... } could not be cloned.
```

**Comment by ldub** [comment]
Also getting this error when using `web3.eth.net.getId()` or `web3.eth.getBlockNumber()` on `1.0.0-beta.48`. Downgrading to `1.0.0-beta.37` does fix it but using an old version isnt a viable solution. would like to see a fix, explanation, or workaround for this.

**Comment by tomsoft1** [comment]
Same issue here, any news....?

**Comment by W3stside** [comment]
`beta.37` is consistently the most stable Web3 beta. Though it still has the memory leak from #1648

**Comment by einaralex** [comment]
I was using web3`beta.48` when I ran into this problem, it worked to downgrade to `beta.37`. Now I upgraded to `beta.55` and that works.

**Comment by Kapn** [comment]
I ran into this problem running `beta.55`. I downgraded to `beta.37` as suggested above and everything is good to go now.

**Comment by danfinlay** [comment]
Closing as this currently sounds like it was a web3.js issue which is likely even resolved by now. Please let us know if it's not.
